parameters:
    open_orchestra_elastica.populator.manager.class: OpenOrchestra\Elastica\Populator\ElasticaPopulatorManager
    open_orchestra_elastica.populator.content.class: OpenOrchestra\Elastica\Populator\Strategies\ContentPopulator

services:
    open_orchestra_elastica.populator.manager:
        class: %open_orchestra_elastica.populator.manager.class%

    open_orchestra_elastica.populator.content:
        class: %open_orchestra_elastica.populator.content.class%
        arguments:
            - @open_orchestra_elastica.indexor.content
            - @open_orchestra_model.repository.content
        tags:
            - { name: open_orchestra_elastica.populator.strategy}
